version: '3'
services:
  doener-order-app:
    build:
     context: .
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "28080:80"
    env_file:
      - doener.env

    #environment:
    #  - MYSQL_USER=root
    #  - MYSQL_PW=
   #   - MYSQL_HOST=192.168.111.187
#      - MYSQL_USER=root
#      - MYSQL_PW=Dvx0TNJMj48yJ9ozFnix
#      - MYSQL_HOST=192.168.0.18:32409
